title: Cyber Angel's Cybersecurity Portfolio
logo: /assets/img/Angelo.pdf
description: A showcase of my skills for my future employer, Showcasing IAM, Risk Management projects and more!
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
