url: "" # the base hostnames & protocol for your site
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme
title: [Cyber Angel's Portfolio of Cyber Security Projects]
description: [Showcase my skills for my future employer.]
